import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

type Page = 'home' | 'product' | 'privacy' | 'terms';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    content: `By accessing or using the QueryNexes AI Model Compilation & Optimization Platform ("Platform"), including any associated websites, APIs, SDKs, documentation, and services (collectively, the "Services"), you agree to be bound by these Terms and Conditions ("Terms"). If you are using the Services on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.

If you do not agree to all provisions of these Terms, you must not access or use the Services. Continued use of the Services following any modification to these Terms constitutes your acceptance of the modified Terms.`,
  },
  {
    title: '2. Description of Service',
    content: `QueryNexes provides an AI model compilation and optimization platform that transforms experimental machine learning models into production-ready, hardware-optimized assets. The Platform supports multiple ML frameworks and hardware targets, offering compilation, benchmarking, and deployment capabilities.

The Services are provided on a subscription basis with varying tiers of functionality, performance, and support. Specific service levels, feature availability, and usage limits are defined in your selected plan and corresponding Service Level Agreement (SLA), which is incorporated herein by reference.

QueryNexes reserves the right to modify, suspend, or discontinue any aspect of the Services at any time, with reasonable notice to affected users, except in cases of emergency security measures or legal requirements.`,
  },
  {
    title: '3. User Accounts and Registration',
    content: `To access the Services, you must create an account by providing accurate, current, and complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.

Account Security: You must notify QueryNexes immediately of any unauthorized use of your account or any other breach of security. We employ multi-factor authentication (MFA) and recommend you enable it for all accounts.

Account Types: Individual accounts are for single-user access. Organization accounts may include administrative controls, team management features, and usage pooling. You may not share account access beyond the number of authorized users specified in your plan.

You must be at least 18 years of age or the age of majority in your jurisdiction to create an account. Accounts registered by automated tools or bots are strictly prohibited.`,
  },
  {
    title: '4. Acceptable Use',
    content: `You agree to use the Services only for lawful purposes and in accordance with these Terms. Prohibited activities include:

Model Restrictions: You may not upload, compile, or distribute models designed for malicious purposes, including but not limited to those intended for surveillance without consent, autonomous weapons systems, generation of harmful or deceptive content, or violation of any applicable laws or regulations.

Platform Abuse: You may not attempt to disrupt, degrade, or impair the Services through excessive API calls, reverse engineering, penetration testing without prior written authorization, or any activity that imposes an unreasonable load on our infrastructure.

Data Compliance: You are solely responsible for ensuring that any data, code, or models you submit to the platform comply with all applicable laws, including data protection, export control, and intellectual property laws.

Intellectual Property: You may not use the Services to infringe upon the intellectual property rights of others, including copyright, patent, trademark, or trade secret protections.`,
  },
  {
    title: '5. Intellectual Property Rights',
    content: `Ownership of Submitted Models: You retain all right, title, and interest in and to the machine learning models, code, and data you submit to the Platform for compilation ("User Content"). QueryNexes claims no ownership over your User Content.

Platform IP: The QueryNexes Platform, including its compilation engine, optimization algorithms, SDKs, APIs, documentation, trade secrets, trademarks, and any derivative works, is the exclusive intellectual property of QueryNexes, Inc. You are granted a limited, non-exclusive, non-transferable, revocable license to use the Services in accordance with these Terms.

Compiled Artifacts: Compiled model artifacts generated by the Platform may incorporate QueryNexes optimization techniques and runtime components. Your use of these artifacts is subject to the license terms specified in your service agreement.

Feedback: Any suggestions, enhancement requests, or feedback you provide regarding the Services may be used by QueryNexes without obligation or compensation to you.`,
  },
  {
    title: '6. Payment Terms',
    content: `Fees: Subscription fees are as specified in your chosen plan and are billed in advance on a monthly or annual basis, as selected during registration. Fees are non-refundable except as expressly stated in these Terms or required by applicable law.

Payment Processing: All payments are processed securely through Stripe, Inc. QueryNexes does not store full payment card information. You authorize us to charge your designated payment method for all fees incurred.

Taxes: You are responsible for all applicable taxes, duties, and governmental assessments associated with your use of the Services, excluding taxes based on QueryNexes' net income.

Late Payment: Fees not paid when due are subject to a late charge of 1.5% per month or the maximum permitted by law, whichever is less. QueryNexes reserves the right to suspend access to the Services for accounts that are more than 15 days past due.`,
  },
  {
    title: '7. Service Availability and SLA',
    content: `Uptime Commitment: QueryNexes commits to a Platform uptime of 99.9% for Enterprise plans, 99.5% for Professional plans, and 99.0% for Starter plans, calculated on a monthly basis.

Scheduled Maintenance: We reserve the right to perform scheduled maintenance during designated maintenance windows. We will provide at least 48 hours' notice for scheduled maintenance that may affect service availability.

Credits: If we fail to meet our uptime commitment, you may request service credits as specified in your SLA. Credits are applied to future invoices and do not constitute a refund.

Force Majeure: QueryNexes is not liable for service interruptions caused by factors outside our reasonable control, including natural disasters, acts of terrorism, war, labor disputes, internet service provider failures, or third-party infrastructure outages.`,
  },
  {
    title: '8. Confidentiality',
    content: `Definition: "Confidential Information" means any non-public information disclosed by one party to the other, whether orally or in writing, that is designated as confidential or reasonably should be understood to be confidential given the nature of the information and circumstances of disclosure.

Obligations: Each party agrees to hold the other's Confidential Information in strict confidence, to use it only for purposes of performing under these Terms, and to disclose it only to employees and contractors who need to know and are bound by confidentiality obligations at least as protective as those herein.

Exceptions: Confidential Information does not include information that: (a) is or becomes publicly available through no fault of the receiving party; (b) was rightfully in the receiving party's possession prior to disclosure; (c) is independently developed by the receiving party without use of the disclosing party's Confidential Information; or (d) is required to be disclosed by law or court order.`,
  },
  {
    title: '9. Limitation of Liability',
    content: `To the maximum extent permitted by applicable law, neither QueryNexes nor its officers, directors, employees, or affiliates shall be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, use, goodwill, or business interruption, arising out of or related to your use of the Services, even if advised of the possibility of such damages.

Our total cumulative liability for any claims arising under these Terms shall not exceed the total fees paid by you to QueryNexes in the twelve (12) months preceding the event giving rise to the liability.

This limitation of liability applies regardless of the theory of liability, whether in contract, tort, strict liability, or otherwise. Some jurisdictions do not allow the exclusion or limitation of certain damages, so the above limitations may not apply to you.`,
  },
  {
    title: '10. Indemnification',
    content: `You agree to defend, indemnify, and hold harmless QueryNexes, its affiliates, licensors, and service providers from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to:

(a) your use of the Services in violation of these Terms;
(b) your User Content, including any claim that your content infringes or violates third-party rights;
(c) your violation of any applicable law, regulation, or third-party agreement;
(d) any dispute between you and another user of the Platform.

QueryNexes reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will cooperate with us in asserting any available defenses.`,
  },
  {
    title: '11. Termination',
    content: `Termination by You: You may terminate your account at any time through the platform dashboard or by contacting our support team. Termination is effective immediately upon processing. Fees paid for the current billing period are non-refundable.

Termination by QueryNexes: We may suspend or terminate your access to the Services immediately, without prior notice or liability, for any material breach of these Terms, including violation of acceptable use policies, non-payment of fees, or activities that threaten the security or integrity of the Platform.

Effect of Termination: Upon termination, your right to access and use the Services ceases immediately. We will retain your data for 90 days following termination, during which you may request export of your User Content. After 90 days, all data will be permanently deleted in accordance with our data retention policies.

Survival: Provisions regarding intellectual property, confidentiality, limitation of liability, indemnification, and governing law shall survive termination of these Terms.`,
  },
  {
    title: '12. Governing Law and Dispute Resolution',
    content: `Governing Law: These Terms shall be governed by and construed in accordance with the laws of the State of California, United States, without regard to its conflict of law provisions.

Dispute Resolution: Any dispute arising out of or relating to these Terms or the Services shall first be resolved through good-faith negotiations between the parties. If the dispute cannot be resolved within 30 days, it shall be submitted to binding arbitration administered by the American Arbitration Association under its Commercial Arbitration Rules.

Arbitration shall be conducted in San Francisco, California, and judgment on the arbitration award may be entered in any court having jurisdiction. Each party shall bear its own costs and attorneys' fees, unless the arbitrator determines that a party has prevailing claims or defenses.

Class Action Waiver: All disputes shall be resolved on an individual basis, and you waive any right to participate in any class action, consolidated proceeding, or representative action against QueryNexes.`,
  },
  {
    title: '13. Contact Information',
    content: `For questions, concerns, or notices regarding these Terms, please contact us at:

Legal Inquiries: legal@querynexes.io
General Support: support@querynexes.io

Mailing Address:
QueryNexes, Inc.
548 Market Street, PMB 98210
San Francisco, CA 94104
United States

Notices to QueryNexes must be sent to the mailing address above with a copy to legal@querynexes.io. Notices will be deemed given when received.`,
  },
];

export default function TermsConditions({ onNavigate, muted, onMuteToggle }: {
  onNavigate: (page: Page) => void;
  muted?: boolean;
  onMuteToggle?: () => void;
}) {
  return (
    <>
      <Navbar currentPage="terms" onNavigate={onNavigate} muted={muted} onMuteToggle={onMuteToggle} />
      <main>
        <section
          style={{
            padding: '120px 48px 64px',
            background: 'var(--bg-primary)',
            borderBottom: '1px solid var(--border-default)',
            position: 'relative',
            overflow: 'hidden',
          }}
          className="legal-hero"
        >
          {/* Background decorative elements */}
          <div style={{
            position: 'absolute', inset: 0, pointerEvents: 'none', overflow: 'hidden',
          }}>
            <div className="legal-grid-bg" />
            <div style={{
              position: 'absolute', top: '-40%', right: '-10%',
              width: '500px', height: '500px',
              borderRadius: '50%',
              background: 'radial-gradient(circle, rgba(0,255,133,0.06) 0%, transparent 70%)',
              pointerEvents: 'none',
            }} />
            <div style={{
              position: 'absolute', bottom: '-20%', left: '-5%',
              width: '300px', height: '300px',
              borderRadius: '50%',
              background: 'radial-gradient(circle, rgba(45,211,255,0.04) 0%, transparent 70%)',
              pointerEvents: 'none',
            }} />
            <div className="legal-particle legal-particle-1" />
            <div className="legal-particle legal-particle-2" />
            <div className="legal-particle legal-particle-3" />
          </div>
          <div className="legal-hero-accent" />

          <span className="section-label" style={{ display: 'block', marginBottom: '12px', position: 'relative', zIndex: 1 }}>
            // LEGAL
          </span>
          <h1
            className="section-title"
            style={{
              fontFamily: 'Space Grotesk, sans-serif',
              fontWeight: 700,
              fontSize: 'clamp(32px, 5vw, 52px)',
              color: 'var(--text-primary)',
              lineHeight: 1.15,
              marginBottom: '16px',
              maxWidth: '720px',
              position: 'relative', zIndex: 1,
            }}
          >
            Terms &amp; Conditions
          </h1>
          <p
            className="section-sub"
            style={{
              fontSize: 'clamp(15px, 2vw, 18px)',
              color: 'var(--text-muted)',
              lineHeight: 1.7,
              maxWidth: '600px',
              marginBottom: 0,
              position: 'relative', zIndex: 1,
            }}
          >
            The terms governing your use of the QueryNexes AI Model Compilation
            &amp; Optimization Platform and related services.
          </p>
        </section>

        <section
          style={{
            padding: '72px 48px 96px',
            background: 'var(--bg-secondary)',
          }}
          className="legal-content"
        >
          <div
            style={{
              maxWidth: '840px',
              margin: '0 auto',
              display: 'flex',
              flexDirection: 'column',
              gap: '28px',
            }}
          >
            {SECTIONS.map((section, i) => (
              <div
                key={i}
                style={{
                  background: 'var(--bg-surface)',
                  border: '1px solid var(--border-default)',
                  borderLeft: '3px solid var(--green-neon)',
                  borderRadius: '12px',
                  padding: '32px',
                }}
              >
                <h2
                  style={{
                    fontFamily: 'Space Grotesk, sans-serif',
                    fontWeight: 600,
                    fontSize: 'clamp(18px, 2vw, 22px)',
                    color: 'var(--green-neon)',
                    marginBottom: '16px',
                    letterSpacing: '-0.01em',
                  }}
                >
                  {section.title}
                </h2>
                {section.content.split('\n\n').map((paragraph, j) => (
                  <p
                    key={j}
                    style={{
                      fontSize: 'clamp(14px, 1.5vw, 16px)',
                      color: 'var(--text-secondary)',
                      lineHeight: 1.8,
                      marginBottom: j < section.content.split('\n\n').length - 1 ? '16px' : 0,
                    }}
                  >
                    {paragraph}
                  </p>
                ))}
              </div>
            ))}
          </div>
        </section>
      </main>
      <Footer onNavigate={onNavigate} />

      <style>{`
        .legal-hero-accent {
          position: absolute;
          bottom: 0;
          left: 0;
          right: 0;
          height: 1px;
          background: linear-gradient(90deg, transparent, var(--green-neon), transparent);
          opacity: 0.3;
        }
        .legal-grid-bg {
          position: absolute;
          inset: 0;
          background-image:
            linear-gradient(rgba(0,255,133,0.03) 1px, transparent 1px),
            linear-gradient(90deg, rgba(0,255,133,0.03) 1px, transparent 1px);
          background-size: 60px 60px;
          mask-image: radial-gradient(ellipse at 50% 0%, black 30%, transparent 70%);
          -webkit-mask-image: radial-gradient(ellipse at 50% 0%, black 30%, transparent 70%);
        }
        .legal-particle {
          position: absolute;
          width: 4px;
          height: 4px;
          border-radius: 50%;
          background: var(--green-neon);
          opacity: 0;
          pointer-events: none;
        }
        .legal-particle-1 {
          top: 20%;
          left: 15%;
          animation: legal-float 6s ease-in-out infinite;
          animation-delay: 0s;
        }
        .legal-particle-2 {
          top: 60%;
          right: 20%;
          width: 3px;
          height: 3px;
          animation: legal-float 8s ease-in-out infinite;
          animation-delay: 2s;
        }
        .legal-particle-3 {
          top: 35%;
          left: 60%;
          width: 5px;
          height: 5px;
          animation: legal-float 7s ease-in-out infinite;
          animation-delay: 4s;
        }
        @keyframes legal-float {
          0%, 100% {
            opacity: 0;
            transform: translateY(0) scale(0.5);
          }
          25% {
            opacity: 0.4;
          }
          50% {
            opacity: 0.6;
            transform: translateY(-20px) scale(1);
          }
          75% {
            opacity: 0.2;
          }
        }
        @media (max-width: 768px) {
          .legal-hero { padding: 100px 24px 48px !important; }
          .legal-content { padding: 48px 24px 64px !important; }
          .legal-content div { gap: 20px !important; }
          .legal-content div > div { padding: 24px !important; }
        }
        @media (max-width: 425px) {
          .legal-hero { padding: 88px 16px 40px !important; }
          .legal-content { padding: 40px 16px 48px !important; }
          .legal-content div > div { padding: 20px !important; }
        }
        @media (max-width: 375px) {
          .legal-hero { padding: 80px 12px 32px !important; }
          .legal-content { padding: 32px 12px 40px !important; }
        }
      `}</style>
    </>
  );
}
